import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
'auth.signInButton': 'Sign In',
'auth.signUpButton': 'Sign Up',
'auth.resetPasswordButton': 'Reset Password',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Password',
'auth.passwordConfirmedFormField': 'Confirmed Password',
'auth.passwordConfirmedFailedTitlte': 'Unmatched Confirmed Password',
'auth.passwordConfirmedFailedMessage': 'The confirmed password does not match',
'auth.nameFormField': 'Name',
'auth.organisationFormField': 'Organisation',
'auth.signInErrorTitle': 'Sign In Error',
'auth.signInError': 'Login failed: email or password incorrect.',
'auth.resetPasswordLabelButton': 'Forgot password?',
'auth.signUpLabelButton': 'Create an account',
'auth.signUpErrorTitle': 'Sign Up Failed.',
'auth.signUpError': 'There was a problem signing up.  Please try again later.',
'auth.signInLabelButton': 'Have an Account? Sign In.',
'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
'auth.resetPasswordNotice': 'Check your email and follow the instructions to reset your password.',
'auth.resetPasswordFailed': 'Password Reset Email Failed',
'auth.signInonResetPasswordLabelButton': 'Sign In',
'auth.updateUser': 'Update Profile',
'auth.updateUserSuccessNoticeTitle': 'User Updated',
'auth.updateUserSuccessNotice': 'User information successfully updated.',
'auth.updateUserEmailInUse': 'That email address already has an account.',
'auth.updateUserFailNotice': 'Failed to update user',
'auth.enterPassword': 'Enter your password',
'auth.cancel': 'Cancel',
'auth.submit': 'Submit',
'auth.changePasswordLabelButton': 'Change Password',
'auth.resetPasswordTitle': 'Reset Password',
'auth.updateProfileTitle': 'Update Profile',
'auth.wrongPasswordNoticeTitle': 'Login Failed',
'auth.wrongPasswordNotice': 'The password does not match our records.',
'auth.unknownError': 'Unknown Error',
'auth.resetPasswordMessage': 'Please enter your email address to reset the password',
'auth.resetPasswordConfirmedMessage': 'A reset password email has been sent to your email at: ',
'settings.title': 'Settings',
'settings.language': 'Language',
'settings.theme': 'Theme',
'settings.signOut': 'Sign Out',
'settings.dark': 'Dark',
'settings.light': 'Light',
'settings.system': 'System',
'settings.updateProfile': 'Update Profile',
'home.title': 'Home',
'home.nameLabel': 'Name',
'home.organisationLabel': 'Organisation',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Admin User',
'app.title': 'Flutter Starter Project',
'validator.email': 'Please enter a valid email address.',
'validator.password': 'Password must be at least 6 characters.',
'validator.passwordConfirmed': 'The confirmed password does not match',
'validator.name': 'Please enter a name.',
'validator.number': 'Please enter a number.',
'validator.notEmpty': 'This is a required field.',
'validator.amount': 'Please enter a number i.e. 250 - no dollar symbol and no cents',
'home.uidLabel': 'Identity',
'profile.title': 'User Profile',
'dashboard.title': 'Dashboard',
'drawer.userProfile': 'User Profile',
'drawer.signOut': 'Sign Out',
'drawer.hightScore': 'Hight Score',
'drawer.training': 'Training',
'drawer.settings': 'Settings',
'drawer.help': 'Help & Feedback',
'drawer.about': 'About',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Sharing',
'settings.sharing.message': 'Allow to share my score with:',
'settings.sharing.organisation': 'My organisation',
'settings.sharing.community': 'MI Cyberrange Community',
'settings.sharing.geiger': 'Geiger platform',
'settings.sharing.button': 'Configure',
'settings.general.title': 'General',
'settings.playerProfile.title': 'Player Profile',
'settings.playerProfile.message': 'Setup player profile',
'settings.playerProfile.template': 'Only use email template',
'settings.playerProfile.registeredEmail': 'Use my registered email',
'settings.playerProfile.custom': 'Customized profile',
'settings.playerProfile.button': 'Setup profile',
},
'vi': {
'auth.signInButton': 'Đăng nhập',
'auth.signUpButton': 'Đăng ký',
'auth.resetPasswordButton': 'Đặt lại mật khẩu',
'auth.emailFormField': 'E-mail',
'auth.passwordFormField': 'Mật khẩu',
'auth.passwordConfirmedFormField': 'Xác nhận mật khẩu',
'auth.passwordConfirmedFailedTitlte': 'Mật khẩu xác nhận chưa từng có',
'auth.passwordConfirmedFailedMessage': 'Mật khẩu được xác nhận không khớp',
'auth.nameFormField': 'Tên',
'auth.organisationFormField': 'Tổ chức',
'auth.signInErrorTitle': 'Đăng nhập LRI.',
'auth.signInError': 'Đăng nhập thất bại: email hoặc mật khẩu không chính xác.',
'auth.resetPasswordLabelButton': 'Quên mật khẩu?',
'auth.signUpLabelButton': 'Tạo một tài khoản',
'auth.signUpErrorTitle': 'Đăng ky thât bại.',
'auth.signUpError': 'Có một vấn đề đăng ký. Vui lòng thử lại sau.',
'auth.signInLabelButton': 'Có một tài khoản? Đăng nhập.',
'auth.resetPasswordNoticeTitle': 'Email đặt lại mật khẩu đã gửi',
'auth.resetPasswordNotice': 'Kiểm tra email của bạn và làm theo hướng dẫn để đặt lại mật khẩu của bạn.',
'auth.resetPasswordFailed': 'Email đặt lại mật khẩu không thành công',
'auth.signInonResetPasswordLabelButton': 'Đăng nhập',
'auth.updateUser': 'Cập nhật hồ sơ',
'auth.updateUserSuccessNoticeTitle': 'Người dùng cập nhật',
'auth.updateUserSuccessNotice': 'Thông tin người dùng được cập nhật thành công.',
'auth.updateUserEmailInUse': 'Địa chỉ email đó đã có một tài khoản.',
'auth.updateUserFailNotice': 'Không thể cập nhật người dùng',
'auth.enterPassword': 'Nhập mật khẩu của bạn',
'auth.cancel': 'Hủy bỏ',
'auth.submit': 'Gửi đi',
'auth.changePasswordLabelButton': 'Đổi mật khẩu',
'auth.resetPasswordTitle': 'Đặt lại mật khẩu',
'auth.updateProfileTitle': 'Cập nhật hồ sơ',
'auth.wrongPasswordNoticeTitle': 'Đăng nhập thất bại',
'auth.wrongPasswordNotice': 'Mật khẩu không khớp với hồ sơ của chúng tôi.',
'auth.unknownError': 'Lỗi không xác định',
'auth.resetPasswordMessage': 'Vui lòng nhập địa chỉ email của bạn để đặt lại mật khẩu',
'auth.resetPasswordConfirmedMessage': 'Một email mật khẩu thiết lập lại đã được gửi đến email của bạn tại:',
'settings.title': 'Cài đặt',
'settings.language': 'Ngôn ngữ',
'settings.theme': 'Chủ đề',
'settings.signOut': 'Đăng xuất',
'settings.dark': 'Tối',
'settings.light': 'Ánh sáng',
'settings.system': 'Hệ thống',
'settings.updateProfile': 'Cập nhật hồ sơ',
'home.title': 'Trang Chủ',
'home.nameLabel': 'Tên',
'home.organisationLabel': 'Tổ chức',
'home.emailLabel': 'E-mail',
'home.adminUserLabel': 'Người dùng quản trị viên',
'app.title': 'Dự án khởi động Flutter',
'validator.email': 'Vui lòng nhập một địa chỉ email hợp lệ.',
'validator.password': 'Mật khẩu phải có ít nhất 6 ký tự.',
'validator.passwordConfirmed': 'Mật khẩu được xác nhận không khớp',
'validator.name': 'Vui lòng nhập tên.',
'validator.number': 'Vui lòng nhập một số.',
'validator.notEmpty': 'Đây là một lĩnh vực cần thiết.',
'validator.amount': 'Vui lòng nhập một số I.E. 250 - Không có biểu tượng đô la và không có xu',
'home.uidLabel': 'Xác thực',
'profile.title': 'Thông tin người dùng',
'dashboard.title': 'bảng điều khiển',
'drawer.userProfile': 'Thông tin người dùng',
'drawer.signOut': 'Đăng xuất',
'drawer.hightScore': 'Điểm cao',
'drawer.training': 'Tập huấn',
'drawer.settings': 'Cài đặt',
'drawer.help': 'Trợ giúp & Phản hồi',
'drawer.about': 'Về',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Chia sẻ',
'settings.sharing.message': 'Cho phép chia sẻ điểm số của tôi với:',
'settings.sharing.organisation': 'Tổ chức của tôi',
'settings.sharing.community': 'Mi cyberrange cộng đồng',
'settings.sharing.geiger': 'Nền tảng Geiger',
'settings.sharing.button': 'Cấu hình.',
'settings.general.title': 'Chung',
'settings.playerProfile.title': 'Hồ sơ người chơi',
'settings.playerProfile.message': 'Cấu hình người chơi thiết lập',
'settings.playerProfile.template': 'Chỉ sử dụng mẫu email',
'settings.playerProfile.registeredEmail': 'Sử dụng email đã đăng ký của tôi',
'settings.playerProfile.custom': 'Hồ sơ tùy chỉnh',
'settings.playerProfile.button': 'Hồ sơ thiết lập.',
},
'fr': {
'auth.signInButton': 'S\'identifier',
'auth.signUpButton': 'S\'inscrire',
'auth.resetPasswordButton': 'réinitialiser le mot de passe',
'auth.emailFormField': 'E-mail',
'auth.passwordFormField': 'Mot de passe',
'auth.passwordConfirmedFormField': 'Mot de passe confirmé',
'auth.passwordConfirmedFailedTitlte': 'Mot de passe confirmé inégalé',
'auth.passwordConfirmedFailedMessage': 'Le mot de passe confirmé ne correspond pas',
'auth.nameFormField': 'Nom',
'auth.organisationFormField': 'Organisation',
'auth.signInErrorTitle': 'Connectez-vous une erreur',
'auth.signInError': 'La connexion a échoué: e-mail ou mot de passe incorrect.',
'auth.resetPasswordLabelButton': 'Mot de passe oublié?',
'auth.signUpLabelButton': 'Créer un compte',
'auth.signUpErrorTitle': 'Inscrivez-vous échoué.',
'auth.signUpError': 'Il y avait un problème d\'inscription. Veuillez réessayer plus tard.',
'auth.signInLabelButton': 'Avoir un compte? S\'identifier.',
'auth.resetPasswordNoticeTitle': 'Mot de passe Réinitialiser le courrier électronique envoyé',
'auth.resetPasswordNotice': 'Vérifiez votre email et suivez les instructions pour réinitialiser votre mot de passe.',
'auth.resetPasswordFailed': 'Mot de passe Reset Email a échoué',
'auth.signInonResetPasswordLabelButton': 'S\'identifier',
'auth.updateUser': 'Mettre à jour le profil',
'auth.updateUserSuccessNoticeTitle': 'Mise à jour de l\'utilisateur',
'auth.updateUserSuccessNotice': 'Informations de l\'utilisateur mis à jour avec succès.',
'auth.updateUserEmailInUse': 'Cette adresse électronique a déjà un compte.',
'auth.updateUserFailNotice': 'Échec de la mise à jour de l\'utilisateur',
'auth.enterPassword': 'Tapez votre mot de passe',
'auth.cancel': 'Annuler',
'auth.submit': 'Soumettre',
'auth.changePasswordLabelButton': 'Changer le mot de passe',
'auth.resetPasswordTitle': 'réinitialiser le mot de passe',
'auth.updateProfileTitle': 'Mettre à jour le profil',
'auth.wrongPasswordNoticeTitle': 'Échec de la connexion',
'auth.wrongPasswordNotice': 'Le mot de passe ne correspond pas à nos enregistrements.',
'auth.unknownError': 'Erreur inconnue',
'auth.resetPasswordMessage': 'Veuillez entrer votre adresse e-mail pour réinitialiser le mot de passe.',
'auth.resetPasswordConfirmedMessage': 'Un email de mot de passe de réinitialisation a été envoyé à votre email à l\'adresse suivante:',
'settings.title': 'Paramètres',
'settings.language': 'Langue',
'settings.theme': 'Thème',
'settings.signOut': 'Se déconnecter',
'settings.dark': 'Sombre',
'settings.light': 'Léger',
'settings.system': 'Système',
'settings.updateProfile': 'Mettre à jour le profil',
'home.title': 'Domicile',
'home.nameLabel': 'Nom',
'home.organisationLabel': 'Organisation',
'home.emailLabel': 'E-mail',
'home.adminUserLabel': 'Utilisateur admin',
'app.title': 'Projet de démarrage à flutter',
'validator.email': 'S\'il vous plaît, mettez une adresse email valide.',
'validator.password': 'Le mot de passe doit être au moins de 6 caractères.',
'validator.passwordConfirmed': 'Le mot de passe confirmé ne correspond pas',
'validator.name': 'S\'il vous plaît entrer un nom.',
'validator.number': 'S\'il vous plaît entrer un numéro.',
'validator.notEmpty': 'Ceci est un champ obligatoire.',
'validator.amount': 'S\'il vous plaît entrer un numéro I.e. 250 - aucun symbole dollar et pas de cents',
'home.uidLabel': 'Identité',
'profile.title': 'Profil de l\'utilisateur',
'dashboard.title': 'Tableau de bord',
'drawer.userProfile': 'Profil de l\'utilisateur',
'drawer.signOut': 'Se déconnecter',
'drawer.hightScore': 'Score de hauteur',
'drawer.training': 'Entraînement',
'drawer.settings': 'Paramètres',
'drawer.help': 'Aide et commentaires',
'drawer.about': 'À propos de',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Partage',
'settings.sharing.message': 'Laisser partager mon score avec:',
'settings.sharing.organisation': 'Mon organisation',
'settings.sharing.community': 'Mi Cyberrange Communauté',
'settings.sharing.geiger': 'Plate-forme Geiger',
'settings.sharing.button': 'Configurer',
'settings.general.title': 'Général',
'settings.playerProfile.title': 'Profil du joueur',
'settings.playerProfile.message': 'Profil du joueur de configuration',
'settings.playerProfile.template': 'Utilisez uniquement le modèle de messagerie',
'settings.playerProfile.registeredEmail': 'Utilisez mon email enregistré',
'settings.playerProfile.custom': 'Profil personnalisé',
'settings.playerProfile.button': 'Profil de configuration',
},
'es': {
'auth.signInButton': 'Registrarse',
'auth.signUpButton': 'Inscribirse',
'auth.resetPasswordButton': 'Restablecer la contraseña',
'auth.emailFormField': 'Correo electrónico',
'auth.passwordFormField': 'Clave',
'auth.passwordConfirmedFormField': 'Contraseña confirmada',
'auth.passwordConfirmedFailedTitlte': 'Contraseña confirmada inigualable',
'auth.passwordConfirmedFailedMessage': 'La contraseña confirmada no coincide',
'auth.nameFormField': 'Nombre',
'auth.organisationFormField': 'Organización',
'auth.signInErrorTitle': 'Error',
'auth.signInError': 'Error de inicio de sesión: correo electrónico o contraseña incorrecta.',
'auth.resetPasswordLabelButton': '¿Se te olvidó tu contraseña?',
'auth.signUpLabelButton': 'Crea una cuenta',
'auth.signUpErrorTitle': 'Registro fallido.',
'auth.signUpError': 'Hubo un problema registrándolo. Por favor, inténtelo de nuevo más tarde.',
'auth.signInLabelButton': '¿Tener una cuenta? Registrarse.',
'auth.resetPasswordNoticeTitle': 'Restablecimiento de contraseña Correo electrónico enviado',
'auth.resetPasswordNotice': 'Revise su correo electrónico y siga las instrucciones para restablecer su contraseña.',
'auth.resetPasswordFailed': 'Falló el correo electrónico de restablecimiento de la contraseña',
'auth.signInonResetPasswordLabelButton': 'Registrarse',
'auth.updateUser': 'Actualización del perfil',
'auth.updateUserSuccessNoticeTitle': 'Usuario actualizado',
'auth.updateUserSuccessNotice': 'Información del usuario actualizada con éxito.',
'auth.updateUserEmailInUse': 'Esa dirección de correo electrónico ya tiene una cuenta.',
'auth.updateUserFailNotice': 'Error al actualizar el usuario',
'auth.enterPassword': 'Ingresa tu contraseña',
'auth.cancel': 'Cancelar',
'auth.submit': 'Entregar',
'auth.changePasswordLabelButton': 'Cambiar la contraseña',
'auth.resetPasswordTitle': 'Restablecer la contraseña',
'auth.updateProfileTitle': 'Actualización del perfil',
'auth.wrongPasswordNoticeTitle': 'Error de inicio de sesion',
'auth.wrongPasswordNotice': 'La contraseña no coincide con nuestros registros.',
'auth.unknownError': 'Error desconocido',
'auth.resetPasswordMessage': 'Por favor ingrese su dirección de correo electrónico para restablecer la contraseña',
'auth.resetPasswordConfirmedMessage': 'Un correo electrónico de restablecimiento de contraseña se ha enviado a su correo electrónico a:',
'settings.title': 'Ajustes',
'settings.language': 'Idioma',
'settings.theme': 'Tema',
'settings.signOut': 'Desconectar',
'settings.dark': 'Oscuro',
'settings.light': 'Luz',
'settings.system': 'Sistema',
'settings.updateProfile': 'Actualización del perfil',
'home.title': 'Casa',
'home.nameLabel': 'Nombre',
'home.organisationLabel': 'Organización',
'home.emailLabel': 'Correo electrónico',
'home.adminUserLabel': 'Administrador',
'app.title': 'Proyecto de inicio de aleteador',
'validator.email': 'Por favor, introduce una dirección de correo electrónico válida.',
'validator.password': 'La contraseña debe tener al menos 6 caracteres.',
'validator.passwordConfirmed': 'La contraseña confirmada no coincide',
'validator.name': 'Por favor ingrese un nombre.',
'validator.number': 'Por favor, introduzca un número.',
'validator.notEmpty': 'Este es un campo obligatorio.',
'validator.amount': 'Por favor ingrese un número I.E. 250 - Sin símbolo de dólar y sin centavos',
'home.uidLabel': 'Identidad',
'profile.title': 'Perfil del usuario',
'dashboard.title': 'Panel',
'drawer.userProfile': 'Perfil del usuario',
'drawer.signOut': 'Desconectar',
'drawer.hightScore': 'Puntaje de altura',
'drawer.training': 'Capacitación',
'drawer.settings': 'Ajustes',
'drawer.help': 'Ayuda y retroalimentación',
'drawer.about': 'Acerca de',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Intercambio',
'settings.sharing.message': 'Permitir compartir mi puntuación con:',
'settings.sharing.organisation': 'Mi organización',
'settings.sharing.community': 'Comunidad CyberRange MI',
'settings.sharing.geiger': 'Plataforma geiger',
'settings.sharing.button': 'Configurar',
'settings.general.title': 'General',
'settings.playerProfile.title': 'Perfil del jugador',
'settings.playerProfile.message': 'Configuración del perfil del jugador',
'settings.playerProfile.template': 'Solo usar plantilla de correo electrónico',
'settings.playerProfile.registeredEmail': 'Usa mi correo electrónico registrado',
'settings.playerProfile.custom': 'Perfil personalizado',
'settings.playerProfile.button': 'Perfil de configuración',
},
'de': {
'auth.signInButton': 'Einloggen',
'auth.signUpButton': 'Anmeldung',
'auth.resetPasswordButton': 'Passwort zurücksetzen',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Passwort',
'auth.passwordConfirmedFormField': 'Passwort bestätigt',
'auth.passwordConfirmedFailedTitlte': 'Unübertroffenes bestätigtes Passwort',
'auth.passwordConfirmedFailedMessage': 'Das bestätigte Kennwort stimmt nicht überein',
'auth.nameFormField': 'Name',
'auth.organisationFormField': 'Organisation',
'auth.signInErrorTitle': 'Fehler anmelden',
'auth.signInError': 'Login fehlgeschlagen: E-Mail oder Passwort falsch.',
'auth.resetPasswordLabelButton': 'Passwort vergessen?',
'auth.signUpLabelButton': 'Ein Konto erstellen',
'auth.signUpErrorTitle': 'Anmeldung gescheitert.',
'auth.signUpError': 'Es gab ein Problem, das sich anmeldet. Bitte versuchen Sie es später erneut.',
'auth.signInLabelButton': 'Ein Konto haben? Einloggen.',
'auth.resetPasswordNoticeTitle': 'Passwort zurücksetzen E-Mail senden',
'auth.resetPasswordNotice': 'Überprüfen Sie Ihre E-Mail und befolgen Sie die Anweisungen, um Ihr Passwort zurückzusetzen.',
'auth.resetPasswordFailed': 'Die E-Mail-Adresse des Kennworts zurücksetzen fehlgeschlagen',
'auth.signInonResetPasswordLabelButton': 'Einloggen',
'auth.updateUser': 'Profil aktualisieren',
'auth.updateUserSuccessNoticeTitle': 'Benutzeraktualisierung',
'auth.updateUserSuccessNotice': 'Benutzerinformationen erfolgreich aktualisiert.',
'auth.updateUserEmailInUse': 'Diese E-Mail-Adresse hat bereits ein Konto.',
'auth.updateUserFailNotice': 'Benutzer konnte nicht aktualisiert werden',
'auth.enterPassword': 'Geben Sie Ihr Passwort ein',
'auth.cancel': 'Stornieren',
'auth.submit': 'einreichen',
'auth.changePasswordLabelButton': 'Ändere das Passwort',
'auth.resetPasswordTitle': 'Passwort zurücksetzen',
'auth.updateProfileTitle': 'Profil aktualisieren',
'auth.wrongPasswordNoticeTitle': 'Fehler bei der Anmeldung',
'auth.wrongPasswordNotice': 'Das Passwort entspricht nicht zu unseren Datensätzen.',
'auth.unknownError': 'Unbekannter Fehler',
'auth.resetPasswordMessage': 'Bitte geben Sie Ihre E-Mail-Adresse ein, um das Passwort zurückzusetzen',
'auth.resetPasswordConfirmedMessage': 'Eine Reset-Kennwort-E-Mail wurde an Ihre E-Mail gesendet, um:',
'settings.title': 'Einstellungen',
'settings.language': 'Sprache',
'settings.theme': 'Thema',
'settings.signOut': 'Austragen',
'settings.dark': 'Dunkel',
'settings.light': 'Licht',
'settings.system': 'System',
'settings.updateProfile': 'Profil aktualisieren',
'home.title': 'Heim',
'home.nameLabel': 'Name',
'home.organisationLabel': 'Organisation',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Admin-Benutzer',
'app.title': 'Flatternstarterprojekt.',
'validator.email': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
'validator.password': 'Passwort muss mindestens 6 Zeichen lang sein.',
'validator.passwordConfirmed': 'Das bestätigte Kennwort stimmt nicht überein',
'validator.name': 'Bitte geben Sie einen Namen ein.',
'validator.number': 'Bitte gebe eine Nummer ein.',
'validator.notEmpty': 'Dies ist ein Pflichtfeld.',
'validator.amount': 'Bitte geben Sie eine Nummer ein, d. H. 250 - Kein Dollarsymbol und keine Cents',
'home.uidLabel': 'Identität',
'profile.title': 'Benutzerprofil',
'dashboard.title': 'Armaturenbrett',
'drawer.userProfile': 'Benutzerprofil',
'drawer.signOut': 'Austragen',
'drawer.hightScore': 'Hight Score.',
'drawer.training': 'Ausbildung',
'drawer.settings': 'Einstellungen',
'drawer.help': 'Hilfe & Feedback.',
'drawer.about': 'Über',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Teilen',
'settings.sharing.message': 'Erlauben Sie meine Punktzahl mit:',
'settings.sharing.organisation': 'Meine Organisation',
'settings.sharing.community': 'Mi Cyberrange Community.',
'settings.sharing.geiger': 'Geiger-Plattform',
'settings.sharing.button': 'Konfigurieren',
'settings.general.title': 'Allgemein',
'settings.playerProfile.title': 'Spielerprofil',
'settings.playerProfile.message': 'Setup-Player-Profil',
'settings.playerProfile.template': 'Verwenden Sie nur E-Mail-Vorlage',
'settings.playerProfile.registeredEmail': 'Verwenden Sie meine registrierte E-Mail',
'settings.playerProfile.custom': 'Kundenspezifisches Profil.',
'settings.playerProfile.button': 'Setup-Profil',
},
'ro': {
'auth.signInButton': 'Conectare',
'auth.signUpButton': 'Inscrie-te',
'auth.resetPasswordButton': 'Reseteaza parola',
'auth.emailFormField': 'E-mail',
'auth.passwordFormField': 'Parola',
'auth.passwordConfirmedFormField': 'Parola confirmată',
'auth.passwordConfirmedFailedTitlte': 'Parolă confirmată de neegalat',
'auth.passwordConfirmedFailedMessage': 'Parola confirmată nu se potrivește',
'auth.nameFormField': 'Nume',
'auth.organisationFormField': 'Organizare',
'auth.signInErrorTitle': 'Conectați-vă de eroare',
'auth.signInError': 'Conectarea a eșuat: e-mail sau parolă incorectă.',
'auth.resetPasswordLabelButton': 'Ați uitat parola?',
'auth.signUpLabelButton': 'Creați un cont',
'auth.signUpErrorTitle': 'Inregistrarea a esuat.',
'auth.signUpError': 'A apărut o problemă de înscriere. Vă rugăm să încercați din nou mai târziu.',
'auth.signInLabelButton': 'Are un cont? Conectare.',
'auth.resetPasswordNoticeTitle': 'Password Resetați e-mail trimis',
'auth.resetPasswordNotice': 'Verificați adresa dvs. de e-mail și urmați instrucțiunile pentru a reseta parola.',
'auth.resetPasswordFailed': 'Resetarea parolei Email a eșuat',
'auth.signInonResetPasswordLabelButton': 'Conectare',
'auth.updateUser': 'Actualizare profil',
'auth.updateUserSuccessNoticeTitle': 'User actualizat',
'auth.updateUserSuccessNotice': 'Informațiile despre utilizatori actualizate cu succes.',
'auth.updateUserEmailInUse': 'Această adresă de e-mail are deja un cont.',
'auth.updateUserFailNotice': 'Nu a reușit să actualizeze utilizatorul',
'auth.enterPassword': 'Introduceți parola',
'auth.cancel': 'Anulare',
'auth.submit': 'Trimite',
'auth.changePasswordLabelButton': 'Schimbați parola',
'auth.resetPasswordTitle': 'Reseteaza parola',
'auth.updateProfileTitle': 'Actualizare profil',
'auth.wrongPasswordNoticeTitle': 'Autentificare eșuată',
'auth.wrongPasswordNotice': 'Parola nu corespunde înregistrărilor noastre.',
'auth.unknownError': 'Eroare necunoscută',
'auth.resetPasswordMessage': 'Introduceți adresa dvs. de e-mail pentru a reseta parola',
'auth.resetPasswordConfirmedMessage': 'Un e-mail de resetare a parolei a fost trimis la adresa dvs. de e-mail la adresa:',
'settings.title': 'Setări.',
'settings.language': 'Limba',
'settings.theme': 'Temă',
'settings.signOut': 'Sign out',
'settings.dark': 'Întuneric',
'settings.light': 'Ușoară',
'settings.system': 'Sistem',
'settings.updateProfile': 'Actualizare profil',
'home.title': 'Acasă',
'home.nameLabel': 'Nume',
'home.organisationLabel': 'Organizare',
'home.emailLabel': 'E-mail',
'home.adminUserLabel': 'Utilizator de admin',
'app.title': 'Flutter Starter Project.',
'validator.email': 'Te rog introdu o adresa de email valida.',
'validator.password': 'Parola trebuie sa aibă cel puțin 6 caractere.',
'validator.passwordConfirmed': 'Parola confirmată nu se potrivește',
'validator.name': 'Introduceți un nume.',
'validator.number': 'Introduceți un număr.',
'validator.notEmpty': 'Acest câmp este obligatoriu.',
'validator.amount': 'Introduceți un număr I.E. 250 - Niciun simbol al dolarului și noți cenți',
'home.uidLabel': 'Identitate',
'profile.title': 'Profilul utilizatorului',
'dashboard.title': 'Bord',
'drawer.userProfile': 'Profilul utilizatorului',
'drawer.signOut': 'Sign out',
'drawer.hightScore': 'Scorul de greutăți',
'drawer.training': 'Instruire',
'drawer.settings': 'Setări.',
'drawer.help': 'Ajutor și feedback',
'drawer.about': 'Despre',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Partajare',
'settings.sharing.message': 'Permiteți împărtășirea scorului meu cu:',
'settings.sharing.organisation': 'Organizația mea',
'settings.sharing.community': 'MI Cyberrange Community.',
'settings.sharing.geiger': 'Platforma Geiger.',
'settings.sharing.button': 'Configurați',
'settings.general.title': 'General',
'settings.playerProfile.title': 'Profilul jucătorului',
'settings.playerProfile.message': 'Configurați profilul jucătorului',
'settings.playerProfile.template': 'Utilizați numai șablonul de e-mail',
'settings.playerProfile.registeredEmail': 'Utilizați e-mailul meu înregistrat',
'settings.playerProfile.custom': 'Profil personalizat',
'settings.playerProfile.button': 'Profil de configurare',
},
'pt': {
'auth.signInButton': 'Entrar',
'auth.signUpButton': 'Inscrever-se',
'auth.resetPasswordButton': 'Redefinir senha',
'auth.emailFormField': 'E-mail',
'auth.passwordFormField': 'Senha',
'auth.passwordConfirmedFormField': 'Senha confirmada',
'auth.passwordConfirmedFailedTitlte': 'Senha confirmada inigualável',
'auth.passwordConfirmedFailedMessage': 'A senha confirmada não corresponde',
'auth.nameFormField': 'Nome',
'auth.organisationFormField': 'Organização',
'auth.signInErrorTitle': 'Entre em erro',
'auth.signInError': 'Falha no login: Email ou senha incorreta.',
'auth.resetPasswordLabelButton': 'Esqueceu sua senha?',
'auth.signUpLabelButton': 'Crie a sua conta aqui',
'auth.signUpErrorTitle': 'Inscreva-se falhou.',
'auth.signUpError': 'Houve um problema em se inscrever. Por favor, tente novamente mais tarde.',
'auth.signInLabelButton': 'Ter uma conta? Entrar.',
'auth.resetPasswordNoticeTitle': 'Senha redefinir email enviado',
'auth.resetPasswordNotice': 'Verifique seu e-mail e siga as instruções para redefinir sua senha.',
'auth.resetPasswordFailed': 'O e-mail de redefinição de senha falhou',
'auth.signInonResetPasswordLabelButton': 'Entrar',
'auth.updateUser': 'Atualizar perfil',
'auth.updateUserSuccessNoticeTitle': 'Usuário atualizado',
'auth.updateUserSuccessNotice': 'Informações do usuário atualizadas com êxito.',
'auth.updateUserEmailInUse': 'Esse endereço de e-mail já tem uma conta.',
'auth.updateUserFailNotice': 'Falha ao atualizar o usuário',
'auth.enterPassword': 'Coloque sua senha',
'auth.cancel': 'Cancelar',
'auth.submit': 'Enviar',
'auth.changePasswordLabelButton': 'Mudar senha',
'auth.resetPasswordTitle': 'Redefinir senha',
'auth.updateProfileTitle': 'Atualizar perfil',
'auth.wrongPasswordNoticeTitle': 'Falha no login',
'auth.wrongPasswordNotice': 'A senha não corresponde aos nossos registros.',
'auth.unknownError': 'Erro desconhecido',
'auth.resetPasswordMessage': 'Por favor, digite seu endereço de e-mail para redefinir a senha',
'auth.resetPasswordConfirmedMessage': 'Um e-mail de senha de redefinição foi enviado para o seu email em:',
'settings.title': 'Configurações',
'settings.language': 'Língua',
'settings.theme': 'Tema',
'settings.signOut': 'Sair',
'settings.dark': 'Escuro',
'settings.light': 'Luz',
'settings.system': 'Sistema',
'settings.updateProfile': 'Atualizar perfil',
'home.title': 'Lar',
'home.nameLabel': 'Nome',
'home.organisationLabel': 'Organização',
'home.emailLabel': 'E-mail',
'home.adminUserLabel': 'Usuário do administrador.',
'app.title': 'Projeto Starter Flutter.',
'validator.email': 'Por favor insira um endereço de e-mail válido.',
'validator.password': 'A senha deve ter pelo menos 6 caracteres.',
'validator.passwordConfirmed': 'A senha confirmada não corresponde',
'validator.name': 'Por favor, insira um nome.',
'validator.number': 'Por favor, coloque um numero.',
'validator.notEmpty': 'Este é um campo obrigatório.',
'validator.amount': 'Por favor, insira um número I.E. 250 - sem símbolo do dólar e sem centavos',
'home.uidLabel': 'Identidade',
'profile.title': 'Perfil de usuário',
'dashboard.title': 'Painel',
'drawer.userProfile': 'Perfil de usuário',
'drawer.signOut': 'Sair',
'drawer.hightScore': 'Pontuação de Hight.',
'drawer.training': 'Treinamento',
'drawer.settings': 'Configurações',
'drawer.help': 'Ajuda e feedback',
'drawer.about': 'Cerca de',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Compartilhamento',
'settings.sharing.message': 'Permitir compartilhar minha pontuação com:',
'settings.sharing.organisation': 'Minha organização',
'settings.sharing.community': 'MI Cyberrange Community.',
'settings.sharing.geiger': 'Plataforma Geiger.',
'settings.sharing.button': 'Configurar.',
'settings.general.title': 'Em geral',
'settings.playerProfile.title': 'Perfil do jogador',
'settings.playerProfile.message': 'Perfil do player de configuração',
'settings.playerProfile.template': 'Use apenas o modelo de e-mail',
'settings.playerProfile.registeredEmail': 'Use meu e-mail registrado',
'settings.playerProfile.custom': 'Perfil personalizado',
'settings.playerProfile.button': 'Configurar perfil',
},
'it': {
'auth.signInButton': 'Registrazione',
'auth.signUpButton': 'Iscrizione',
'auth.resetPasswordButton': 'Resetta la password',
'auth.emailFormField': 'E-mail',
'auth.passwordFormField': 'Parola d\'ordine',
'auth.passwordConfirmedFormField': 'Password confermata',
'auth.passwordConfirmedFailedTitlte': 'Password confermata senza corrispondenza',
'auth.passwordConfirmedFailedMessage': 'La password confermata non corrisponde',
'auth.nameFormField': 'Nome',
'auth.organisationFormField': 'Organizzazione',
'auth.signInErrorTitle': 'Accedi Errore',
'auth.signInError': 'Login non riuscito: e-mail o password errati.',
'auth.resetPasswordLabelButton': 'Ha dimenticato la password?',
'auth.signUpLabelButton': 'Crea un account',
'auth.signUpErrorTitle': 'Accesso fallito.',
'auth.signUpError': 'C\'è stato un problema che iscrivesse. Per favore riprova più tardi.',
'auth.signInLabelButton': 'Avere un conto? Registrazione.',
'auth.resetPasswordNoticeTitle': 'Password Reset Email inviata',
'auth.resetPasswordNotice': 'Controlla la tua email e segui le istruzioni per ripristinare la password.',
'auth.resetPasswordFailed': 'Password Reset Email non riuscita',
'auth.signInonResetPasswordLabelButton': 'Registrazione',
'auth.updateUser': 'Aggiorna il profilo',
'auth.updateUserSuccessNoticeTitle': 'Utente aggiornato',
'auth.updateUserSuccessNotice': 'Informazioni dell\'utente aggiornate correttamente.',
'auth.updateUserEmailInUse': 'Questo indirizzo email ha già un account.',
'auth.updateUserFailNotice': 'Impossibile aggiornare l\'utente',
'auth.enterPassword': 'Inserisci la tua password',
'auth.cancel': 'Annulla',
'auth.submit': 'Invia',
'auth.changePasswordLabelButton': 'Cambiare la password',
'auth.resetPasswordTitle': 'Resetta la password',
'auth.updateProfileTitle': 'Aggiorna il profilo',
'auth.wrongPasswordNoticeTitle': 'Accesso non riuscito',
'auth.wrongPasswordNotice': 'La password non corrisponde ai nostri record.',
'auth.unknownError': 'Errore sconosciuto',
'auth.resetPasswordMessage': 'Inserisci il tuo indirizzo email per reimpostare la password',
'auth.resetPasswordConfirmedMessage': 'Un\'e-mail di reset password è stata inviata alla tua email a:',
'settings.title': 'Impostazioni',
'settings.language': 'Lingua',
'settings.theme': 'Tema',
'settings.signOut': 'Disconnessione',
'settings.dark': 'Buio',
'settings.light': 'Leggero',
'settings.system': 'Sistema',
'settings.updateProfile': 'Aggiorna il profilo',
'home.title': 'Casa',
'home.nameLabel': 'Nome',
'home.organisationLabel': 'Organizzazione',
'home.emailLabel': 'E-mail',
'home.adminUserLabel': 'Utente admin',
'app.title': 'Project Flutter Starter.',
'validator.email': 'Si prega di inserire un indirizzo email valido.',
'validator.password': 'La password deve essere di almeno 6 caratteri.',
'validator.passwordConfirmed': 'La password confermata non corrisponde',
'validator.name': 'Si prega di inserire un nome.',
'validator.number': 'Per favore inserisci un numero.',
'validator.notEmpty': 'Questo è un campo obbligatorio.',
'validator.amount': 'Si prega di inserire un numero I.E. 250 - nessun simbolo del dollaro e nessun centesimo',
'home.uidLabel': 'Identità',
'profile.title': 'Profilo utente',
'dashboard.title': 'Pannello di controllo',
'drawer.userProfile': 'Profilo utente',
'drawer.signOut': 'Disconnessione',
'drawer.hightScore': 'Hight Punteggio',
'drawer.training': 'Addestramento',
'drawer.settings': 'Impostazioni',
'drawer.help': 'Aiuto e feedback',
'drawer.about': 'Di',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Condivisione',
'settings.sharing.message': 'Permetti di condividere il mio punteggio con:',
'settings.sharing.organisation': 'La mia organizzazione',
'settings.sharing.community': 'MI Cyberrange Community.',
'settings.sharing.geiger': 'Piattaforma Geiger',
'settings.sharing.button': 'Configura.',
'settings.general.title': 'Generale',
'settings.playerProfile.title': 'Profilo del giocatore',
'settings.playerProfile.message': 'Profilo del giocatore di installazione',
'settings.playerProfile.template': 'Utilizzare solo il modello di posta elettronica',
'settings.playerProfile.registeredEmail': 'Usa la mia email registrata',
'settings.playerProfile.custom': 'Profilo personalizzato',
'settings.playerProfile.button': 'Setup Profilo.',
},
'ja': {
'auth.signInButton': 'ログイン',
'auth.signUpButton': 'サインアップ',
'auth.resetPasswordButton': 'パスワードを再設定する',
'auth.emailFormField': 'Eメール',
'auth.passwordFormField': 'パスワード',
'auth.passwordConfirmedFormField': '確認されたパスワード',
'auth.passwordConfirmedFailedTitlte': '比類のない確認されたパスワード',
'auth.passwordConfirmedFailedMessage': '確認されたパスワードが一致しません',
'auth.nameFormField': '名前',
'auth.organisationFormField': '組織',
'auth.signInErrorTitle': 'エラー',
'auth.signInError': 'ログインに失敗しました：電子メールまたはパスワードが正しくありません。',
'auth.resetPasswordLabelButton': 'パスワードをお忘れですか？',
'auth.signUpLabelButton': 'アカウントを作成する',
'auth.signUpErrorTitle': 'サインアップに失敗しました。',
'auth.signUpError': 'サインアップが起こりました。後でもう一度やり直してください。',
'auth.signInLabelButton': 'アカウントを持っています？ログイン。',
'auth.resetPasswordNoticeTitle': 'パスワードリセットメール送信',
'auth.resetPasswordNotice': '電子メールを確認して、指示に従ってパスワードをリセットしてください。',
'auth.resetPasswordFailed': 'パスワードリセットEメールに失敗しました',
'auth.signInonResetPasswordLabelButton': 'ログイン',
'auth.updateUser': 'プロファイルを更新します',
'auth.updateUserSuccessNoticeTitle': 'ユーザーが更新されました',
'auth.updateUserSuccessNotice': 'ユーザー情報は正常に更新されました。',
'auth.updateUserEmailInUse': 'そのEメールアドレスはすでにアカウントを持っています。',
'auth.updateUserFailNotice': 'ユーザーの更新に失敗しました',
'auth.enterPassword': 'パスワードを入力してください',
'auth.cancel': 'キャンセル',
'auth.submit': '送信',
'auth.changePasswordLabelButton': 'パスワードを変更する',
'auth.resetPasswordTitle': 'パスワードを再設定する',
'auth.updateProfileTitle': 'プロファイルを更新します',
'auth.wrongPasswordNoticeTitle': 'ログインに失敗しました',
'auth.wrongPasswordNotice': 'パスワードは私たちの記録と一致しません。',
'auth.unknownError': '未知のエラー',
'auth.resetPasswordMessage': 'パスワードをリセットするには、Eメールアドレスを入力してください',
'auth.resetPasswordConfirmedMessage': 'パスワードのリセット電子メールがあなたのEメールに送信されました：',
'settings.title': '設定',
'settings.language': '言語',
'settings.theme': 'テーマ',
'settings.signOut': 'サインアウト',
'settings.dark': '暗い',
'settings.light': '光',
'settings.system': 'システム',
'settings.updateProfile': 'プロファイルを更新します',
'home.title': '家',
'home.nameLabel': '名前',
'home.organisationLabel': '組織',
'home.emailLabel': 'Eメール',
'home.adminUserLabel': '管理ユーザー',
'app.title': 'フラッタースタータープロジェクト',
'validator.email': '有効なメールアドレスを入力してください。',
'validator.password': 'パスワードは少なくとも6文字でなければなりません。',
'validator.passwordConfirmed': '確認されたパスワードが一致しません',
'validator.name': '名前を入力してください。',
'validator.number': '数字を入力してください。',
'validator.notEmpty': 'これは必要項目です。',
'validator.amount': '番号すなわち250  - ドル記号とセントなし',
'home.uidLabel': '身元',
'profile.title': 'ユーザープロファイル',
'dashboard.title': 'ダッシュボード',
'drawer.userProfile': 'ユーザープロファイル',
'drawer.signOut': 'サインアウト',
'drawer.hightScore': 'ハイトスコア',
'drawer.training': 'トレーニング',
'drawer.settings': '設定',
'drawer.help': 'ヘルプ＆フィードバック',
'drawer.about': '約',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': '共用する',
'settings.sharing.message': 'スコアを共有できるようにします。',
'settings.sharing.organisation': '私の組織',
'settings.sharing.community': 'Mi Cyber​​Range Community',
'settings.sharing.geiger': 'ガイガープラットフォーム',
'settings.sharing.button': '構成、設定',
'settings.general.title': '全般的',
'settings.playerProfile.title': 'プレイヤープロファイル',
'settings.playerProfile.message': 'プレーヤープロファイルを設定します',
'settings.playerProfile.template': '電子メールテンプレートのみを使用してください',
'settings.playerProfile.registeredEmail': '私の登録されたEメールを使用してください',
'settings.playerProfile.custom': 'カスタマイズされたプロファイル',
'settings.playerProfile.button': 'セットアッププロファイル',
},
'nl': {
'auth.signInButton': 'Inloggen',
'auth.signUpButton': 'Inschrijven',
'auth.resetPasswordButton': 'Wachtwoord opnieuw instellen',
'auth.emailFormField': 'E-mail',
'auth.passwordFormField': 'Wachtwoord',
'auth.passwordConfirmedFormField': 'Bevestigd wachtwoord',
'auth.passwordConfirmedFailedTitlte': 'Ongeëvenaard bevestigd wachtwoord',
'auth.passwordConfirmedFailedMessage': 'Het bevestigde wachtwoord komt niet overeen',
'auth.nameFormField': 'Naam',
'auth.organisationFormField': 'Organisatie',
'auth.signInErrorTitle': 'Meld je aan',
'auth.signInError': 'Inloggen mislukt: e-mail of wachtwoord onjuist.',
'auth.resetPasswordLabelButton': 'Wachtwoord vergeten?',
'auth.signUpLabelButton': 'Account aanmaken',
'auth.signUpErrorTitle': 'Registratie mislukt.',
'auth.signUpError': 'Er was een probleem dat zich aanmeldt. Probeer het later opnieuw.',
'auth.signInLabelButton': 'Een account hebben? Inloggen.',
'auth.resetPasswordNoticeTitle': 'Wachtwoord Reset E-mail verzonden',
'auth.resetPasswordNotice': 'Controleer uw e-mail en volg de instructies om uw wachtwoord opnieuw in te stellen.',
'auth.resetPasswordFailed': 'Wachtwoord Reset-e-mail mislukt',
'auth.signInonResetPasswordLabelButton': 'Inloggen',
'auth.updateUser': 'Profiel bijwerken',
'auth.updateUserSuccessNoticeTitle': 'Gebruiker bijgewerkt',
'auth.updateUserSuccessNotice': 'Gebruikersinformatie succesvol bijgewerkt.',
'auth.updateUserEmailInUse': 'Dat e-mailadres heeft al een account.',
'auth.updateUserFailNotice': 'Kan de gebruiker niet bijwerken',
'auth.enterPassword': 'Voer uw wachtwoord in',
'auth.cancel': 'Annuleren',
'auth.submit': 'Indienen',
'auth.changePasswordLabelButton': 'Wijzig wachtwoord',
'auth.resetPasswordTitle': 'Wachtwoord opnieuw instellen',
'auth.updateProfileTitle': 'Profiel bijwerken',
'auth.wrongPasswordNoticeTitle': 'Aanmelden mislukt',
'auth.wrongPasswordNotice': 'Het wachtwoord komt niet overeen met onze records.',
'auth.unknownError': 'Onbekende fout',
'auth.resetPasswordMessage': 'Voer uw e-mailadres in om het wachtwoord opnieuw in te stellen',
'auth.resetPasswordConfirmedMessage': 'Een reset-wachtwoord E-mail is verzonden naar uw e-mail op:',
'settings.title': 'Instellingen',
'settings.language': 'Taal',
'settings.theme': 'Thema',
'settings.signOut': 'Afmelden',
'settings.dark': 'Donker',
'settings.light': 'Licht',
'settings.system': 'Systeem',
'settings.updateProfile': 'Profiel bijwerken',
'home.title': 'Thuis',
'home.nameLabel': 'Naam',
'home.organisationLabel': 'Organisatie',
'home.emailLabel': 'E-mail',
'home.adminUserLabel': 'Admin-gebruiker',
'app.title': 'Flutter starter project',
'validator.email': 'Vul een geldig e-mailadres in.',
'validator.password': 'Wachtwoord moet bestaan ​​uit minstens 6 karakters.',
'validator.passwordConfirmed': 'Het bevestigde wachtwoord komt niet overeen',
'validator.name': 'Voer een naam in.',
'validator.number': 'Voer alstublieft een nummer in.',
'validator.notEmpty': 'Dit is een verplicht veld.',
'validator.amount': 'Voer een nummer in. I.E. 250 - Geen dollarsymbool en geen cent',
'home.uidLabel': 'Identiteit',
'profile.title': 'Gebruikersprofiel',
'dashboard.title': 'Dashboard',
'drawer.userProfile': 'Gebruikersprofiel',
'drawer.signOut': 'Afmelden',
'drawer.hightScore': 'Hight-score',
'drawer.training': 'Opleiding',
'drawer.settings': 'Instellingen',
'drawer.help': 'Help en feedback',
'drawer.about': 'Over',
'drawer.header': 'MI Cyberrange',
'settings.sharing.title': 'Het delen',
'settings.sharing.message': 'Laat mijn score delen met:',
'settings.sharing.organisation': 'Mijn organisatie',
'settings.sharing.community': 'MI Cyberrange gemeenschap',
'settings.sharing.geiger': 'Geiger Platform',
'settings.sharing.button': 'Configureren',
'settings.general.title': 'Algemeen',
'settings.playerProfile.title': 'Spelersprofiel',
'settings.playerProfile.message': 'Setup Player-profiel',
'settings.playerProfile.template': 'Gebruik alleen e-mailsjabloon',
'settings.playerProfile.registeredEmail': 'Gebruik mijn geregistreerde e-mail',
'settings.playerProfile.custom': 'Aangepast profiel',
'settings.playerProfile.button': 'Setup-profiel',
},
        };
      }
      